import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        spr: {
          purple: '#581CDC',
          'purple-dark': '#3D0D9E',
          'purple-deep': '#240863',
          gold: '#F5B84A',
          coral: '#F56E7D',
          teal: '#12B3A8',
          cream: '#FAF6F0',
          ink: '#1A1625',
          'page-bg': '#F8F5F0',
          'deep-navy': '#0D1530',
          primary: '#581CDC',
          'primary-dark': '#3D0FA0',
          'primary-light': '#7B4FE0',
          'primary-50': '#F3EFFE',
          'primary-100': '#E0D4FC',
          accent: '#00D4AA',
          'accent-dark': '#00B894',
          navy: '#1A1A2E',
          'navy-dark': '#12122A',
          bg: '#FFFFFF',
          'bg-secondary': '#F5F5FA',
          'bg-tertiary': '#EEEEF5',
          card: '#FFFFFF',
          surface: '#F5F5FA',
          border: '#E2E2EA',
          'border-light': '#F0F0F5',
          text: '#1A1A2E',
          'text-secondary': '#5A5A72',
          'text-muted': '#8A8AA0',
          danger: '#FF6B6B',
          success: '#00D4AA',
          orange: '#FF8C42',
          blue: '#3B82F6',
          // Keep dark theme colors for peta/katalog pages
          dark: '#0A0A1A',
          'dark-card': '#12122A',
          'dark-surface': '#1A1A3A',
          'dark-border': 'rgba(88,28,220,0.25)',
          'dark-text': '#E8E6F0',
          'dark-text-muted': '#9B97B0',
          'dark-text-dim': '#6B6880',
        },
      },
      fontFamily: {
        display: ['Playfair Display', 'Georgia', 'serif'],
        body: ['DM Sans', 'Inter', 'system-ui', 'sans-serif'],
        serif: ['var(--font-inter-tight)', 'system-ui', 'sans-serif'],
        sans: ['var(--font-inter-tight)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
      },
    },
  },
  plugins: [],
};
export default config;
