export interface PartiInfo {
  id: number;
  singkatan: string;
  nama: string;
  region: "Koalisi" | "Semenanjung" | "Sabah" | "Sarawak";
  logo: string;
  warna: string;
}

export const PARTI_FULL_LIST: PartiInfo[] = [
  { id: 1, singkatan: "BN", nama: "Barisan Nasional Of Malaysia", region: "Koalisi", logo: "01_BN_BARISAN_NASIONAL.png", warna: "#004080" },
  { id: 2, singkatan: "UMNO", nama: "Pertubuhan Kebangsaan Melayu Bersatu", region: "Semenanjung", logo: "02_UMNO.png", warna: "#ff0000" },
  { id: 3, singkatan: "MCA", nama: "Malaysian Chinese Association", region: "Semenanjung", logo: "03_MCA.png", warna: "#e6e600" },
  { id: 4, singkatan: "MIC", nama: "The Malaysian Indian Congress", region: "Semenanjung", logo: "04_MIC.png", warna: "#009933" },
  { id: 5, singkatan: "PAS", nama: "Parti Islam Se Malaysia", region: "Semenanjung", logo: "05_PAS.png", warna: "#6CB332" },
  { id: 6, singkatan: "BERSATU", nama: "Parti Pribumi Bersatu Malaysia", region: "Semenanjung", logo: "06_BERSATU.png", warna: "#cc0000" },
  { id: 7, singkatan: "PH", nama: "Pakatan Harapan", region: "Koalisi", logo: "07_PH_PAKATAN_HARAPAN.png", warna: "#d7282f" },
  { id: 8, singkatan: "AMANAH", nama: "Parti Amanah Negara", region: "Semenanjung", logo: "08_AMANAH.png", warna: "#FF9900" },
  { id: 9, singkatan: "PKR", nama: "Parti Keadilan Rakyat", region: "Semenanjung", logo: "09_PKR.png", warna: "#04A0D1" },
  { id: 10, singkatan: "DAP", nama: "Democratic Action Party, Malaysia", region: "Semenanjung", logo: "10_DAP.png", warna: "#E70024" },
  { id: 11, singkatan: "GERAKAN", nama: "Parti Gerakan Rakyat Malaysia", region: "Semenanjung", logo: "11_GERAKAN.png", warna: "#fe2514" },
  { id: 12, singkatan: "KIMMA", nama: "Kongres Indian Muslim Malaysia", region: "Semenanjung", logo: "12_KIMMA.png", warna: "#de8801" },
  { id: 13, singkatan: "MCC", nama: "Malaysian Ceylonese Congress", region: "Semenanjung", logo: "13_MCC.png", warna: "#e65c00" },
  { id: 14, singkatan: "PSM", nama: "Parti Sosialis Malaysia", region: "Semenanjung", logo: "14_PSM.png", warna: "#c0110d" },
  { id: 15, singkatan: "PUTRA", nama: "Parti Bumiputera Perkasa Malaysia", region: "Semenanjung", logo: "15_PUTRA.png", warna: "#4b4b4b" },
  { id: 16, singkatan: "AMIPF", nama: "Barisan Kemajuan India Se-Malaysia", region: "Semenanjung", logo: "16_AMIPF.png", warna: "#e30300" },
  { id: 17, singkatan: "MMSP", nama: "Parti Makkal Sakti Malaysia", region: "Semenanjung", logo: "17_MMSP_MAKKAL_SAKTI.png", warna: "#f2a317" },
  { id: 18, singkatan: "PRM", nama: "Parti Rakyat Malaysia", region: "Semenanjung", logo: "18_PRM.png", warna: "#ca2126" },
  { id: 19, singkatan: "BERJASA", nama: "Barisan Jamaah Islamiah Se Malaysia", region: "Semenanjung", logo: "19_BERJASA.png", warna: "#730947" },
  { id: 20, singkatan: "IKATAN", nama: "Parti Ikatan Bangsa Malaysia", region: "Semenanjung", logo: "20_IKATAN.png", warna: "#e60000" },
  { id: 21, singkatan: "PPM", nama: "Parti Punjabi Malaysia", region: "Semenanjung", logo: "21_PPM_PUNJABI.png", warna: "#cc9900" },
  { id: 22, singkatan: "PCM", nama: "Parti Cinta Malaysia", region: "Semenanjung", logo: "22_PCM_CINTA_MALAYSIA.png", warna: "#F4E50E" },
  { id: 23, singkatan: "PFP", nama: "Penang Front Party", region: "Semenanjung", logo: "23_PFP_PENANG_FRONT.png", warna: "#ff3333" },
  { id: 24, singkatan: "MU", nama: "Parti Bersama Malaysia", region: "Semenanjung", logo: "24_PBM_MU_BERSAMA.png", warna: "#800000" },
  { id: 25, singkatan: "PAP", nama: "Parti Alternatif Rakyat", region: "Semenanjung", logo: "25_PAP_ALTERNATIF.png", warna: "#000d1a" },
  { id: 26, singkatan: "PN", nama: "Perikatan Nasional", region: "Koalisi", logo: "26_PN_PERIKATAN_NASIONAL.png", warna: "#002e4d" },
  { id: 27, singkatan: "MAP", nama: "Parti Kemajuan Malaysia", region: "Semenanjung", logo: "27_MAP_KEMAJUAN.png", warna: "#ffdd00" },
  { id: 28, singkatan: "PEJUANG", nama: "Parti Pejuang Tanahair", region: "Semenanjung", logo: "28_PEJUANG.png", warna: "#0066a6" },
  { id: 29, singkatan: "IMAN", nama: "Parti Perikatan India Muslim Nasional", region: "Semenanjung", logo: "29_IMAN.png", warna: "#BD2828" },
  { id: 30, singkatan: "MUDA", nama: "Ikatan Demokratik Malaysia", region: "Semenanjung", logo: "30_MUDA.png", warna: "#000000" },
  { id: 31, singkatan: "PBM", nama: "Parti Bangsa Malaysia", region: "Semenanjung", logo: "31_PBM_BANGSA_MALAYSIA.png", warna: "#fcf9a8" },
  { id: 32, singkatan: "PUR", nama: "Parti Utama Rakyat", region: "Semenanjung", logo: "32_PUR.png", warna: "#C66E29" },
  { id: 33, singkatan: "PRIM", nama: "Parti Rakyat India Malaysia", region: "Semenanjung", logo: "33_PRIM.png", warna: "#FB6463" },
  { id: 34, singkatan: "ASLI", nama: "Parti Orang Asli Malaysia", region: "Semenanjung", logo: "34_ASLI.png", warna: "#815e22" },
  { id: 35, singkatan: "MYPPP", nama: "Malaysian People's Progressive Party", region: "Semenanjung", logo: "35_MYPPP.png", warna: "#0941ec" },
  { id: 36, singkatan: "GPS", nama: "Gabungan Parti Sarawak", region: "Koalisi", logo: "36_GPS.png", warna: "#ff794d" },
  { id: 37, singkatan: "PSB", nama: "Parti Sarawak Bersatu", region: "Sarawak", logo: "37_PSB.png", warna: "#FF9900" },
  { id: 38, singkatan: "PBB", nama: "Parti Pesaka Bumiputra Bersatu Sarawak", region: "Sarawak", logo: "38_PBB.png", warna: "#f0e98b" },
  { id: 39, singkatan: "SUPP", nama: "Parti Rakyat Bersatu Sarawak", region: "Sarawak", logo: "39_SUPP.png", warna: "#ffff00" },
  { id: 40, singkatan: "PDP", nama: "Parti Demokratik Progresif Sarawak", region: "Sarawak", logo: "40_PDP.png", warna: "#6abfe6" },
  { id: 41, singkatan: "PRS", nama: "Parti Rakyat Sarawak", region: "Sarawak", logo: "41_PRS.png", warna: "#33cc33" },
  { id: 42, singkatan: "PEACE", nama: "People's Alliance for Justice of Peace", region: "Sarawak", logo: "42_PEACE_PARTY_SARAWAK.png", warna: "#661A00" },
  { id: 43, singkatan: "TERAS", nama: "Parti Tenaga Rakyat Sarawak", region: "Sarawak", logo: "43_TERAS.png", warna: "#001A33" },
  { id: 44, singkatan: "ASPIRASI", nama: "Parti Aspirasi Rakyat Sarawak", region: "Sarawak", logo: "44_ASPIRASI.png", warna: "#e63900" },
  { id: 45, singkatan: "PBK", nama: "Party Bumi Kenyalang", region: "Sarawak", logo: "45_PBK.png", warna: "#ffaa00" },
  { id: 46, singkatan: "SEDAR", nama: "Parti Sedar Rakyat Sarawak", region: "Sarawak", logo: "46_SEDAR.png", warna: "#ffff1a" },
  { id: 47, singkatan: "PBDS", nama: "Parti Bansa Dayak Sarawak", region: "Sarawak", logo: "47_PBDS.png", warna: "#e0f810" },
  { id: 48, singkatan: "UPKO", nama: "Pertubuhan Kinabalu Progresif Bersatu", region: "Sabah", logo: "48_UPKO.png", warna: "#2a0e72" },
  { id: 49, singkatan: "WARISAN", nama: "Parti Warisan Sabah", region: "Sabah", logo: "49_WARISAN.png", warna: "#99CCFF" },
  { id: 50, singkatan: "PBRS", nama: "Parti Bersatu Rakyat Sabah", region: "Sabah", logo: "50_PBRS.png", warna: "#f9f906" },
  { id: 51, singkatan: "PBS", nama: "Parti Bersatu Sabah", region: "Sabah", logo: "51_PBS.png", warna: "#6666ff" },
  { id: 52, singkatan: "STARSABAH", nama: "Parti Solidariti Tanah Airku", region: "Sabah", logo: "52_STARSABAH.png", warna: "#4d4dff" },
  { id: 53, singkatan: "LDP", nama: "Parti Liberal Demokratik", region: "Sabah", logo: "53_LDP.png", warna: "#ab3d1a" },
  { id: 54, singkatan: "BERSAMA", nama: "Parti Bersatu Sasa Malaysia", region: "Sabah", logo: "54_BERSAMA.png", warna: "#ff66ff" },
  { id: 55, singkatan: "SAPP", nama: "Parti Maju Sabah", region: "Sabah", logo: "55_SAPP.png", warna: "#fbfd0b" },
  { id: 56, singkatan: "PPRS", nama: "Parti Perpaduan Rakyat Sabah", region: "Sabah", logo: "56_PPRS.png", warna: "#0000ff" },
  { id: 57, singkatan: "USNO", nama: "Pertubuhan Kebangsaan Sabah Bersatu", region: "Sabah", logo: "57_USNO.png", warna: "#003300" },
  { id: 58, singkatan: "ANAK NEGERI", nama: "Parti Kerjasama Anak Negeri", region: "Sabah", logo: "58_ANAK_NEGERI.png", warna: "#000000" },
  { id: 59, singkatan: "PKS", nama: "Parti Kebangsaan Sabah", region: "Sabah", logo: "59_PKS.png", warna: "#0069cc" },
  { id: 60, singkatan: "SAPU", nama: "Parti Sejahtera Angkatan Perpaduan Sabah", region: "Sabah", logo: "60_SAPU.png", warna: "#FF4000" },
  { id: 61, singkatan: "PCS", nama: "Parti Cinta Sabah", region: "Sabah", logo: "61_PCS.png", warna: "#802000" },
  { id: 62, singkatan: "HARAPAN RAKYAT", nama: "Parti Harapan Rakyat Sabah", region: "Sabah", logo: "62_HARAPAN_RAKYAT.png", warna: "#9999ff" },
  { id: 63, singkatan: "PERPADUAN", nama: "Pertubuhan Perpaduan Rakyat Kebangsaan Sabah", region: "Sabah", logo: "63_PERPADUAN.png", warna: "#ffff4d" },
  { id: 64, singkatan: "SPP", nama: "Parti Damai Sabah", region: "Sabah", logo: "64_SPP_DAMAI_SABAH.png", warna: "#006600" },
  { id: 65, singkatan: "PGRS", nama: "Parti Gagasan Rakyat Sabah", region: "Sabah", logo: "65_PGRS.png", warna: "#88B5CC" },
  { id: 66, singkatan: "GRS", nama: "Parti Gabungan Rakyat Sabah", region: "Koalisi", logo: "66_GRS.png", warna: "#6285a8" },
  { id: 67, singkatan: "KDM", nama: "Parti Kesejahteraan Demokratik Masyarakat", region: "Sabah", logo: "67_KDM.png", warna: "#EB7389" },
  { id: 68, singkatan: "PIS", nama: "Parti Impian Sabah", region: "Sabah", logo: "68_PIS.png", warna: "#05d1fa" },
  { id: 69, singkatan: "GAS", nama: "Pertubuhan Parti Gemilang Anak Sabah", region: "Sabah", logo: "69_GAS.png", warna: "#f95d5d" },
  { id: 70, singkatan: "PR", nama: "Perjuangan Rakyat", region: "Sabah", logo: "70_PR_PERJUANGAN_RAKYAT.png", warna: "#fbf309" },
  { id: 71, singkatan: "RUMPUN", nama: "Parti Rumpun Sabah", region: "Sabah", logo: "71_RUMPUN_SABAH.png", warna: "#0cfd08" },
];

export interface BebasInfo {
  id: number;
  nama: string;
  logo: string;
}

export const BEBAS_FULL_LIST: BebasInfo[] = [
  { id: 1, nama: "Gajah", logo: "01_GAJAH.png" },
  { id: 2, nama: "Kuda", logo: "02_KUDA.png" },
  { id: 3, nama: "Kucing", logo: "03_KUCING.png" },
  { id: 4, nama: "Pen", logo: "04_PEN.png" },
  { id: 5, nama: "Buku", logo: "05_BUKU.png" },
  { id: 6, nama: "Traktor", logo: "06_TRAKTOR.png" },
  { id: 7, nama: "Pokok", logo: "07_POKOK.png" },
  { id: 8, nama: "Durian", logo: "08_DURIAN.png" },
  { id: 9, nama: "Rumah", logo: "09_RUMAH.png" },
  { id: 10, nama: "Kunci", logo: "10_KUNCI.png" },
  { id: 11, nama: "Jam", logo: "11_JAM.png" },
  { id: 12, nama: "Telefon", logo: "12_TELEFON.png" },
  { id: 13, nama: "Kerusi", logo: "13_KERUSI.png" },
  { id: 14, nama: "Gitar", logo: "14_GITAR.png" },
  { id: 15, nama: "Kapal Terbang", logo: "15_KAPAL_TERBANG.png" },
  { id: 16, nama: "Kereta", logo: "16_KERETA.png" },
  { id: 17, nama: "Perahu", logo: "17_PERAHU.png" },
  { id: 18, nama: "Motorsikal", logo: "18_MOTORSIKAL.png" },
  { id: 19, nama: "Kereta Api", logo: "19_KERETA_API.png" },
  { id: 20, nama: "Tali Leher", logo: "20_TALI_LEHER.png" },
  { id: 21, nama: "Cermin Mata", logo: "21_CERMIN_MATA.png" },
  { id: 22, nama: "Baju", logo: "22_BAJU.png" },
  { id: 23, nama: "Cincin", logo: "23_CINCIN.png" },
  { id: 24, nama: "Beg", logo: "24_BEG.png" },
  { id: 25, nama: "Berlian", logo: "25_BERLIAN.png" },
  { id: 26, nama: "Komputer", logo: "26_KOMPUTER.png" },
  { id: 27, nama: "Dron", logo: "27_DRON.png" },
  { id: 28, nama: "Badminton", logo: "28_BADMINTON.png" },
  { id: 29, nama: "Bola Sepak", logo: "29_BOLA_SEPAK.png" },
];

export const REGION_BADGE_STYLES: Record<string, { bg: string; text: string }> = {
  Koalisi: { bg: "#EFF6FF", text: "#1D4ED8" },
  Semenanjung: { bg: "#ECFDF5", text: "#059669" },
  Sabah: { bg: "#FFF7ED", text: "#EA580C" },
  Sarawak: { bg: "#F5F3FF", text: "#7C3AED" },
};
